---
- name: Informations
  debug:
    msg: Install Repo

## -------------------------------------
# - 1.Check if EPEL repo is already configured.
# -------------------------------------
- name: 1.Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
## -------------------------------------
# - 2.Install EPEL repo.
# -------------------------------------
- name: 2.Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
## -------------------------------------
# - 3.Import EPEL GPG key.
# -------------------------------------
- name: 3.Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists




